### ISSUE TITLE
rem-calc in the compiled css output

### ISSUE THREAD

**Issue by nilsnh** [netliferesearch/starter#23]
When I try to use the included breakpoint mixin like so:
```sass
@include breakpoint(small, max) {

  .mb-main-nav-list {
    flex-flow: row wrap;
  }
}
```
I get this result in the compiled webpack output (`npm run webpack`):

```css
@media (max-width: rem-calc(480)) {
  .mb-main-nav-list {
    -ms-flex-flow: row wrap;
        flex-flow: row wrap; }
}
```

Rem-calc should not be there. :thinking:
